name: pokemon_cards
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  cupertino_icons: ^1.0.6
  # Add any other packages you use here like animations or sound effects.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Ensure your assets are correctly listed
  assets:
    - assets/background.png
    - assets/splash1.webp
    - assets/splash3.jpg
    # Add other assets like background images, card images, or sounds here

  # Fonts section (add your custom fonts if applicable)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
